name: LEGACY

on: push

jobs:
  test:
    name: Test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["0.8", "0.10", "0.12", "4", "6", "8"]
        os: [ubuntu-16.04]

    steps:
      - uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node }}
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: ${{ matrix.node }}

      - name: Disabling Strict SSL
        run: npm conf set strict-ssl false

      - name: Installing Dependencies
        run: npm install

      - name: Running Tests
        run: npm test
